version: '3.8'

services:
  agentforge:
    build:
      context: .
      dockerfile: Dockerfile.combined
    container_name: agentforge
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Application
      - APP_NAME=AgentForge
      - ENV=${ENV:-development}
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # API Configuration
      - API_HOST=127.0.0.1
      - API_PORT=8000

      # Database
      - DATABASE_URL=sqlite+aiosqlite:///./data/agentforge.db

      # Vector Store
      - CHROMA_PERSIST_DIRECTORY=./data/chroma_data

      # LLM API Keys (REQUIRED - Set these!)
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Embeddings
      - EMBEDDING_MODEL=openai

      # Document Upload
      - MAX_UPLOAD_SIZE_MB=${MAX_UPLOAD_SIZE_MB:-10}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-pdf,txt,md,docx}

      # Rate Limiting
      - CHAT_RATE_LIMIT=${CHAT_RATE_LIMIT:-60}
    volumes:
      - agentforge-data:/app/data
      - chroma-data:/app/data/chroma_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  agentforge-data:
    driver: local
  chroma-data:
    driver: local
